AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
KEY_LOCK_ENABLE = no
LEADER_ENABLE = no
RGBLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
TERMINAL_ENABLE = no
UNICODE_ENABLE = no
VELOCIKEY_ENABLE = no
VIA_ENABLE = no
WPM_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE = yes

BOOTLOADER = qmk-dfu

MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
LTO_ENABLE = yes

SRC += kemonine.c

ifeq ($(KEYBOARD), nullbitsco/tidbit)
	SRC += boards/tidbit.c
endif
