// Copyright (c) 2021 Mike "KemoNine" Crosson
// SPDX-License-Identifier: Apache-2.0
#pragma once

#ifdef ARDUX_HAND_LEFT
#ifdef ARDUX_SIZE_40P
#define F0P_LEADING_NONES
#define F0P_ROW_ONE_MID_NONES
#define F0P_BETWEEN_ROW_ONE_TWO_NONES
#define F0P_ROW_TWO_MID_NONES
#define F0P_BETWEEN_ROW_TWO_THREE_NONES
#define F0P_ROW_THREE_MID_NONES
#define F0P_BETWEEN_ROW_THREE_THUMBS_NONES
#define F0P_THUMB_MID_NONES
#define F0P_TRAILING_NONES
#endif
#define BIG_LEADING_NONES KC_NO,
#define BIG_BETWEEN_ROW_ONE_TWO_NONES LGUI(KC_E), KC_HOME, KC_UP, KC_END, KC_PGUP, KC_BSPC, KC_NO,
#define BIG_BETWEEN_ROW_TWO_THREE_NONES KC_NO, KC_LEFT, KC_DOWN, KC_RIGHT, KC_PGDN, KC_ENT, KC_NO,
#define BIG_BETWEEN_ROW_THREE_THUMBS_NONES KC_NO, KC_SPACE, KC_ESC, KC_NO, KC_ENT, KC_NO,
#define BIG_TRAILING_NONES , KC_SPACE, KC_ESC, KC_NO
#endif

#ifdef ARDUX_HAND_RIGHT
#ifdef ARDUX_SIZE_40P
#define F0P_LEADING_NONES
#define F0P_ROW_ONE_MID_NONES
#define F0P_BETWEEN_ROW_ONE_TWO_NONES
#define F0P_ROW_TWO_MID_NONES
#define F0P_BETWEEN_ROW_TWO_THREE_NONES
#define F0P_ROW_THREE_MID_NONES
#define F0P_BETWEEN_ROW_THREE_THUMBS_NONES
#define F0P_THUMB_MID_NONES
#define F0P_TRAILING_NONES
#endif
#define BIG_LEADING_NONES KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
#define BIG_BETWEEN_ROW_ONE_TWO_NONES KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
#define BIG_BETWEEN_ROW_TWO_THREE_NONES KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
#define BIG_BETWEEN_ROW_THREE_THUMBS_NONES KC_NO, KC_NO, KC_NO, KC_NO,
#define BIG_TRAILING_NONES
#endif

#ifdef ARDUX_TWO_THUMB
#define ARDUX_BIG_LAYER_MSE_LEFT_THUMBS KC_NO, KC_NO
#endif
#ifndef ARDUX_TWO_THUMB
#define ARDUX_BIG_LAYER_MSE_LEFT_THUMBS
#endif

#define ARDUX_BIG_LAYER_MSE_LEFT \
KC_NO, KMSE_T4, KMSE_T3, KMSE_T2, KMSE_T1, KC_NO,        KC_NO, KMSE_T1, KMSE_T2,  KMSE_T3, KMSE_T4, KC_NO, \
KC_NO, KMSE_B4, KMSE_B3, KMSE_B2, KMSE_B1, KC_NO,        KC_NO, KMSE_B3, KMSE_B2,  KMSE_B1, KMSE_B4, KC_NO, \
KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,        KC_NO, KC_NO,   KC_NO,    KC_NO,   KC_NO,   KC_NO, \
                         KC_NO,   KC_NO,   KC_NO,        KC_NO, KC_NO, KC_NO

#define ARDUX_BIG_LAYER_CUS_LEFT_THUMBS KC_NO, KC_NO, KC_NO
#define ARDUX_BIG_LAYER_CUS_LEFT \
BIG_LEADING_NONES \
KC_NO,            KC_VOLU,          KC_SYSTEM_POWER,  KC_WWW_BACK,      KC_INS,  \
BIG_BETWEEN_ROW_ONE_TWO_NONES \
KC_TRNS,          KC_VOLD,          KC_WWW_SEARCH,    KC_MUTE,          KC_PSCR, \
BIG_BETWEEN_ROW_TWO_THREE_NONES \
KC_NO,            KC_NO,            KC_NO,            KC_NO,            KC_NO,   \
BIG_BETWEEN_ROW_THREE_THUMBS_NONES \
ARDUX_BIG_LAYER_CUS_LEFT_THUMBS \
BIG_TRAILING_NONES
