#define TAPPING_TERM 200
#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_LAYERS
#define GRAVE_ESC_CTRL_OVERRIDE

// Mouse settings
#define MOUSEKEY_DELAY 175
#define MOUSEKEY_WHEEL_DELAY 175
#define MOUSEKEY_INTERVAL 20
#define MOUSEKEY_TIME_TO_MAX 15
#define MOUSEKEY_MAX_SPEED 5
#define MOUSEKEY_WHEEL_INTERVAL 50
#define MOUSEKEY_WHEEL_TIME_TO_MAX 20
#define MOUSEKEY_WHEEL_MAX_SPEED 10
